### ISSUE TITLE
As a software developer, I want an updated README.md file, so that other developers can get to know more about my project

### ISSUE THREAD

**Issue by marceljar** [BTS-2023-2024/Group_00#1]
### Description
The README.md file needs to be updated to present basic information about the project at a glance. The required sections for this document are:

- A table presenting the students names, Github handles, email addresses (Seneca), and roles.
- A brief description of the project, followed by a description of its most important tools/functionalities.
- A preliminary list and description of the components that constitute its technological stack.
 
### Acceptance Criteria

- All required sections are present.
- The writing is clear and provides a clear introduction of the project.
- The writing is free of typos and/or grammatical mistakes.

### Testing Criteria
Not applicable.

**Comment by marceljar** [comment]
### Weekly Scrum 

So far, I added the first two required sections of this document: a **table** with students names, and a **brief description** of it. No problems were encountered so far. That said, the list of technological components is bound to be a more complex endeavor.

**Comment by marceljar** [comment]
### Retrospective
Creating this README.md file was more challenging than anticipated. Crafting a brief description initially appeared straightforward. However, as I incorporated tools and functionalities, I recognized the need for frequent alterations to the brief description. Additionally, determining the technologies to include in the project's tech stack early in its development proved to be a considerable challenge. Nevertheless, I am confident that this initial draft of the README.md serves as an excellent starting point for the project, and it should be relatively easy to maintain as the project progresses.

**Comment by sukhmanprit** [comment]
### Retrospective

Building this feature has been more complex than I initially anticipated. While implementing the upload functionality seemed straightforward, integrating it with the admin dashboard required more attention to user experience than I expected. Additionally, ensuring seamless database updates upon status changes proved challenging, but I'm pleased with the progress made so far. Overall, I believe we are on the right track, and I look forward to refining the dashboard and improving its usability as we move forward.

**Comment by marceljar** [comment]
Solved with #2
